language: node_js
node_js:
  - "7"
install:
  - npm install
  - npm install parcel -g
  - parcel build index.html
  - cp -r dist deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: deploy
  target_branch: gh-pages
  email: keao.yang@yahoo.com
  name: YangKao
  fqdn: descartes.life
  on:
    branch: master
